name: Build and publish

on:
  workflow_dispatch

jobs:
  build_pages:
    name: Publish Data via GitHub Pages Website
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Install things
      run: |
        pip install -r requirements.txt
    - name: build html data
      run: |
        mkdir html
        python utils.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./html 